<?php
// Generated by Laminas's ./bin/classmap_generator.php
return array(
    'LaminasBase\Module'                                    => __DIR__ . '/Module.php',
    'LaminasBase\Form\ProvidesEventsForm'                   => __DIR__ . '/src/LaminasBase/Form/ProvidesEventsForm.php',
    'LaminasBase\Mapper\Exception\ExceptionInterface'       => __DIR__ . '/src/LaminasBase/Mapper/Exception/ExceptionInterface.php',
    'LaminasBase\Mapper\Exception\InvalidArgumentException' => __DIR__ . '/src/LaminasBase/Mapper/Exception/InvalidArgumentException.php',
    'LaminasBase\Mapper\AbstractDbMapper'                   => __DIR__ . '/src/LaminasBase/Mapper/AbstractDbMapper.php',
    'LaminasBase\EventManager\EventProvider'                => __DIR__ . '/src/LaminasBase/EventManager/EventProvider.php',
    'LaminasBase\Module\AbstractModule'                     => __DIR__ . '/src/LaminasBase/Module/AbstractModule.php',
);